#!/usr/bin/env bash

DOWNLOADS_DIR="${HOME}/Downloads"
DOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

if test "${1}" = "--trampoline"; then
  echo ">>> Starting watchexec"
  watchexec -w "${DOWNLOADS_DIR}" -e "zip" -r -p "$0"
  exit 0
fi

if test -n "${WATCHEXEC_RENAMED_PATH}"; then
  f="${WATCHEXEC_RENAMED_PATH}"
elif test -n "${WATCHEXEC_CREATED_PATH}"; then
  f="${WATCHEXEC_CREATED_PATH}"
fi
f="${DOWNLOADS_DIR}/$(basename "${f}")"

if test -f "${f}"; then
  if [ "$(echo "${f}" | grep -c 'Roam-Export')" -gt 0 ]; then
    echo "Got export zip from Roam: ${f}"
    
    pushd $(mktemp -d)
      unzip -o "${f}"
      json="$(pwd)/$(find *.json | head -1)"
    popd

    if test -f "$json"; then
      pushd "${DOT}/.."
        eval "$(pyenv init -)"
        source .venv/bin/activate
        roamconfig -t var/test.yaml.j2 -j "${json}" | tee var/test.yaml
        roamconfig -t var/live.yaml.j2 -j "${json}" | tee var/live.yaml
      popd
    fi
  fi
fi
